title: SCCS
description: > 
  The Swarthmore College Computer Society (SCCS) is a student-run group offering 
  computing services, tools, toys, and information to the Swarthmore College 
  community. 
url: "http://sccs.swarthmore.edu" 
destination: /srv/services/homepage

# Add deploy script to copy over mailman_cookie
exclude: ["deploy"]

# CSS stuff
sass:
  sass_dir: _scss
  style: :compressed
